import type { Locale } from '@/components/preferences-provider';

export type UiMessage =
  | 'settingsTitle' | 'settingsDescription' | 'accentTitle' | 'accentDescription'
  | 'preview' | 'primaryAction' | 'selectedItem' | 'languageTitle'
  | 'languageDescription' | 'languageLabel' | 'saveChanges'
  | 'blue' | 'green' | 'red' | 'yellow' | 'purple'
  | 'openSidebar' | 'unlockSidebar' | 'lockSidebar' | 'themeSystem'
  | 'themeLight' | 'themeDark' | 'viewProfile' | 'admin' | 'user'
  | 'dashboard' | 'notifications' | 'changeTheme' | 'navigateOn'
  | 'navigateOff' | 'organizationLogo' | 'customColor' | 'accentPreviewHint'
  | 'languageHelp' | 'logoBackgroundTitle' | 'logoBackgroundHint'
  | 'backgroundNone' | 'backgroundDark' | 'backgroundWhite'
  | 'invalidLogoBackground';

type CatalogMessage = Exclude<UiMessage, 'invalidLogoBackground'>;

const messages: Record<Locale, Record<CatalogMessage, string>> = {
  fa: {
    settingsTitle:'تنظیمات عمومی', settingsDescription:'رنگ اصلی و زبان نمایش برنامه را انتخاب کنید. حالت روشن و تیره از هدر بالا در دسترس است.', accentTitle:'رنگ تم', accentDescription:'با انتخاب هر رنگ، پیش‌نمایش آن فوراً در محیط داخلی اعمال می‌شود. برای نگه‌داشتن آن «ذخیره تغییرات» را بزنید؛ با خروج بدون ذخیره، رنگ قبلی برمی‌گردد.', preview:'پیش‌نمایش', primaryAction:'دکمهٔ اصلی', selectedItem:'گزینهٔ فعال', languageTitle:'زبان نمایش', languageDescription:'فارسی، انگلیسی، عربی، چینی ساده‌شده، فرانسوی، اسپانیایی، آلمانی، روسی، ژاپنی و پرتغالی برزیلی.', languageHelp:'برای تغییر زبان به تنظیمات ← عمومی بروید، زبان را انتخاب کنید و «ذخیره تغییرات» را بزنید.', languageLabel:'زبان', saveChanges:'ذخیره تغییرات', blue:'آبی', green:'سبز', red:'قرمز', yellow:'زرد', purple:'بنفش', customColor:'رنگ سفارشی', accentPreviewHint:'نمونهٔ رنگ انتخاب‌شده', openSidebar:'باز کردن سایدبار', unlockSidebar:'باز کردن قفل سایدبار', lockSidebar:'قفل کردن سایدبار', themeSystem:'حالت فعلی: سیستم', themeLight:'حالت فعلی: روشن', themeDark:'حالت فعلی: تیره', viewProfile:'مشاهده پروفایل در سایدبار', admin:'مدیر', user:'کاربر', dashboard:'رفتن به صفحه اصلی', notifications:'اعلان‌ها', changeTheme:'تغییر تم', navigateOn:'ناوبری خودکار فعال است؛ کلیک روی ماژول صفحه را باز می‌کند', navigateOff:'ناوبری خودکار غیرفعال است؛ کلیک روی ماژول فقط منو را باز می‌کند', organizationLogo:'لوگوی سازمان', logoBackgroundTitle:'پس‌زمینهٔ لوگو', logoBackgroundHint:'پس‌زمینهٔ لوگو در هدر را مشخص کنید.', backgroundNone:'بدون پس‌زمینه', backgroundDark:'پس‌زمینهٔ تیره', backgroundWhite:'پس‌زمینهٔ سفید',
  },
  en: {
    settingsTitle:'General settings', settingsDescription:'Choose the application accent color and display language. Light and dark mode stay available in the top header.', accentTitle:'Accent color', accentDescription:'Selecting a color previews it immediately in the workspace. Choose “Save changes” to keep it; leaving without saving restores the previous color.', preview:'Preview', primaryAction:'Primary action', selectedItem:'Selected item', languageTitle:'Display language', languageDescription:'Persian, English, Arabic, Simplified Chinese, French, Spanish, German, Russian, Japanese, and Brazilian Portuguese.', languageHelp:'To change the language, open Settings → General, select a language, then choose “Save changes”.', languageLabel:'Language', saveChanges:'Save changes', blue:'Blue', green:'Green', red:'Red', yellow:'Yellow', purple:'Purple', customColor:'Custom color', accentPreviewHint:'Selected color preview', openSidebar:'Open sidebar', unlockSidebar:'Unlock sidebar', lockSidebar:'Lock sidebar', themeSystem:'Theme: system', themeLight:'Theme: light', themeDark:'Theme: dark', viewProfile:'View profile in sidebar', admin:'admin', user:'User', dashboard:'Go to dashboard', notifications:'Notifications', changeTheme:'Change theme', navigateOn:'Automatic navigation is on; click a module to open it', navigateOff:'Automatic navigation is off; click a module to open its menu', organizationLogo:'Organization logo', logoBackgroundTitle:'Logo background', logoBackgroundHint:'Choose the background shown behind the logo in the header.', backgroundNone:'No background', backgroundDark:'Dark background', backgroundWhite:'White background',
  },
  ar: {
    settingsTitle:'الإعدادات العامة', settingsDescription:'اختر لون الواجهة ولغة العرض. يتوفر الوضع الفاتح والداكن في الشريط العلوي.', accentTitle:'لون الواجهة', accentDescription:'يُعرض اللون المختار فورًا في مساحة العمل. اختر «حفظ التغييرات» للاحتفاظ به؛ والانتقال دون حفظ يعيد اللون السابق.', preview:'معاينة', primaryAction:'إجراء رئيسي', selectedItem:'عنصر محدد', languageTitle:'لغة العرض', languageDescription:'الفارسية والإنجليزية والعربية والصينية المبسطة والفرنسية والإسبانية والألمانية والروسية واليابانية والبرتغالية البرازيلية.', languageHelp:'لتغيير اللغة، افتح الإعدادات ← عام، واختر اللغة، ثم اضغط «حفظ التغييرات».', languageLabel:'اللغة', saveChanges:'حفظ التغييرات', blue:'أزرق', green:'أخضر', red:'أحمر', yellow:'أصفر', purple:'بنفسجي', customColor:'لون مخصص', accentPreviewHint:'معاينة اللون المحدد', openSidebar:'فتح الشريط الجانبي', unlockSidebar:'إلغاء قفل الشريط الجانبي', lockSidebar:'قفل الشريط الجانبي', themeSystem:'المظهر: النظام', themeLight:'المظهر: فاتح', themeDark:'المظهر: داكن', viewProfile:'عرض الملف الشخصي في الشريط الجانبي', admin:'المسؤول', user:'مستخدم', dashboard:'الانتقال إلى لوحة التحكم', notifications:'الإشعارات', changeTheme:'تغيير المظهر', navigateOn:'التنقل التلقائي مفعّل؛ انقر على الوحدة لفتحها', navigateOff:'التنقل التلقائي متوقف؛ انقر على الوحدة لفتح قائمتها', organizationLogo:'شعار المؤسسة', logoBackgroundTitle:'خلفية الشعار', logoBackgroundHint:'اختر الخلفية التي تظهر خلف الشعار في الشريط العلوي.', backgroundNone:'بلا خلفية', backgroundDark:'خلفية داكنة', backgroundWhite:'خلفية بيضاء',
  },
  'zh-CN': {
    settingsTitle:'常规设置', settingsDescription:'选择界面强调色和显示语言。可在顶部栏切换浅色或深色模式。', accentTitle:'强调色', accentDescription:'选择颜色后会立即在工作区预览。点击“保存更改”以保留；未保存离开会恢复之前的颜色。', preview:'预览', primaryAction:'主要操作', selectedItem:'已选项目', languageTitle:'显示语言', languageDescription:'波斯语、英语、阿拉伯语、简体中文、法语、西班牙语、德语、俄语、日语和巴西葡萄牙语。', languageHelp:'更改语言：打开“设置”→“常规”，选择语言，然后点击“保存更改”。', languageLabel:'语言', saveChanges:'保存更改', blue:'蓝色', green:'绿色', red:'红色', yellow:'黄色', purple:'紫色', customColor:'自定义颜色', accentPreviewHint:'所选颜色预览', openSidebar:'展开侧边栏', unlockSidebar:'解锁侧边栏', lockSidebar:'锁定侧边栏', themeSystem:'主题：跟随系统', themeLight:'主题：浅色', themeDark:'主题：深色', viewProfile:'在侧边栏查看个人资料', admin:'管理员', user:'用户', dashboard:'前往仪表盘', notifications:'通知', changeTheme:'更改主题', navigateOn:'自动导航已开启；点击模块即可打开', navigateOff:'自动导航已关闭；点击模块可打开菜单', organizationLogo:'组织徽标', logoBackgroundTitle:'徽标背景', logoBackgroundHint:'选择顶部栏中徽标后方的背景。', backgroundNone:'无背景', backgroundDark:'深色背景', backgroundWhite:'白色背景',
  },
  fr: {
    settingsTitle:'Paramètres généraux', settingsDescription:'Choisissez la couleur principale et la langue. Le mode clair ou sombre reste accessible dans l’en-tête.', accentTitle:'Couleur principale', accentDescription:'La couleur choisie est prévisualisée immédiatement. Cliquez sur « Enregistrer » pour la conserver ; quitter sans enregistrer rétablit la couleur précédente.', preview:'Aperçu', primaryAction:'Action principale', selectedItem:'Élément sélectionné', languageTitle:'Langue d’affichage', languageDescription:'Persan, anglais, arabe, chinois simplifié, français, espagnol, allemand, russe, japonais et portugais brésilien.', languageHelp:'Pour changer de langue, ouvrez Paramètres → Général, choisissez une langue, puis cliquez sur « Enregistrer les modifications ».', languageLabel:'Langue', saveChanges:'Enregistrer', blue:'Bleu', green:'Vert', red:'Rouge', yellow:'Jaune', purple:'Violet', customColor:'Couleur personnalisée', accentPreviewHint:'Aperçu de la couleur choisie', openSidebar:'Ouvrir le menu', unlockSidebar:'Déverrouiller le menu', lockSidebar:'Verrouiller le menu', themeSystem:'Thème : système', themeLight:'Thème : clair', themeDark:'Thème : sombre', viewProfile:'Voir le profil dans le menu', admin:'administrateur', user:'Utilisateur', dashboard:'Aller au tableau de bord', notifications:'Notifications', changeTheme:'Changer de thème', navigateOn:'Navigation automatique activée ; cliquez sur un module pour l’ouvrir', navigateOff:'Navigation automatique désactivée ; cliquez sur un module pour ouvrir son menu', organizationLogo:'Logo de l’organisation', logoBackgroundTitle:'Arrière-plan du logo', logoBackgroundHint:'Choisissez l’arrière-plan du logo dans l’en-tête.', backgroundNone:'Sans arrière-plan', backgroundDark:'Arrière-plan sombre', backgroundWhite:'Arrière-plan blanc',
  },
  es: {
    settingsTitle:'Configuración general', settingsDescription:'Elige el color principal y el idioma. El modo claro u oscuro está disponible en el encabezado.', accentTitle:'Color principal', accentDescription:'El color elegido se previsualiza al instante. Pulsa «Guardar cambios» para conservarlo; si sales sin guardar, se restaura el color anterior.', preview:'Vista previa', primaryAction:'Acción principal', selectedItem:'Elemento seleccionado', languageTitle:'Idioma de visualización', languageDescription:'Persa, inglés, árabe, chino simplificado, francés, español, alemán, ruso, japonés y portugués brasileño.', languageHelp:'Para cambiar el idioma, ve a Configuración → General, selecciónalo y pulsa «Guardar cambios».', languageLabel:'Idioma', saveChanges:'Guardar cambios', blue:'Azul', green:'Verde', red:'Rojo', yellow:'Amarillo', purple:'Morado', customColor:'Color personalizado', accentPreviewHint:'Vista previa del color elegido', openSidebar:'Abrir menú lateral', unlockSidebar:'Desbloquear menú', lockSidebar:'Bloquear menú', themeSystem:'Tema: sistema', themeLight:'Tema: claro', themeDark:'Tema: oscuro', viewProfile:'Ver perfil en el menú', admin:'administrador', user:'Usuario', dashboard:'Ir al panel', notifications:'Notificaciones', changeTheme:'Cambiar tema', navigateOn:'La navegación automática está activa; haz clic en un módulo para abrirlo', navigateOff:'La navegación automática está desactivada; haz clic en un módulo para abrir su menú', organizationLogo:'Logotipo de la organización', logoBackgroundTitle:'Fondo del logotipo', logoBackgroundHint:'Elige el fondo que se muestra detrás del logotipo en el encabezado.', backgroundNone:'Sin fondo', backgroundDark:'Fondo oscuro', backgroundWhite:'Fondo blanco',
  },
  de: {
    settingsTitle:'Allgemeine Einstellungen', settingsDescription:'Wähle Akzentfarbe und Anzeigesprache. Heller und dunkler Modus sind über die Kopfzeile verfügbar.', accentTitle:'Akzentfarbe', accentDescription:'Die gewählte Farbe wird sofort in der Arbeitsfläche angezeigt. Mit „Änderungen speichern“ bleibt sie erhalten; ohne Speichern wird die vorherige Farbe wiederhergestellt.', preview:'Vorschau', primaryAction:'Hauptaktion', selectedItem:'Ausgewählter Eintrag', languageTitle:'Anzeigesprache', languageDescription:'Persisch, Englisch, Arabisch, vereinfachtes Chinesisch, Französisch, Spanisch, Deutsch, Russisch, Japanisch und brasilianisches Portugiesisch.', languageHelp:'Zum Ändern der Sprache: Einstellungen → Allgemein öffnen, Sprache auswählen und „Änderungen speichern“ wählen.', languageLabel:'Sprache', saveChanges:'Änderungen speichern', blue:'Blau', green:'Grün', red:'Rot', yellow:'Gelb', purple:'Violett', customColor:'Benutzerdefinierte Farbe', accentPreviewHint:'Vorschau der gewählten Farbe', openSidebar:'Seitenleiste öffnen', unlockSidebar:'Seitenleiste entsperren', lockSidebar:'Seitenleiste sperren', themeSystem:'Design: System', themeLight:'Design: Hell', themeDark:'Design: Dunkel', viewProfile:'Profil in der Seitenleiste anzeigen', admin:'Administrator', user:'Benutzer', dashboard:'Zum Dashboard', notifications:'Benachrichtigungen', changeTheme:'Design ändern', navigateOn:'Automatische Navigation ist aktiv; Modul anklicken zum Öffnen', navigateOff:'Automatische Navigation ist aus; Modul anklicken zum Öffnen des Menüs', organizationLogo:'Organisationslogo', logoBackgroundTitle:'Logo-Hintergrund', logoBackgroundHint:'Wähle den Hintergrund hinter dem Logo in der Kopfzeile.', backgroundNone:'Kein Hintergrund', backgroundDark:'Dunkler Hintergrund', backgroundWhite:'Weißer Hintergrund',
  },
  ru: {
    settingsTitle:'Общие настройки', settingsDescription:'Выберите основной цвет и язык интерфейса. Светлая и тёмная темы доступны в верхней панели.', accentTitle:'Основной цвет', accentDescription:'Выбранный цвет сразу отображается в рабочей области. Нажмите «Сохранить изменения», чтобы оставить его; при выходе без сохранения вернётся прежний цвет.', preview:'Предпросмотр', primaryAction:'Основное действие', selectedItem:'Выбранный элемент', languageTitle:'Язык интерфейса', languageDescription:'Персидский, английский, арабский, упрощённый китайский, французский, испанский, немецкий, русский, японский и бразильский португальский.', languageHelp:'Чтобы изменить язык, откройте Настройки → Общие, выберите язык и нажмите «Сохранить изменения».', languageLabel:'Язык', saveChanges:'Сохранить изменения', blue:'Синий', green:'Зелёный', red:'Красный', yellow:'Жёлтый', purple:'Фиолетовый', customColor:'Свой цвет', accentPreviewHint:'Предпросмотр выбранного цвета', openSidebar:'Открыть боковую панель', unlockSidebar:'Разблокировать панель', lockSidebar:'Заблокировать панель', themeSystem:'Тема: системная', themeLight:'Тема: светлая', themeDark:'Тема: тёмная', viewProfile:'Открыть профиль в боковой панели', admin:'администратор', user:'Пользователь', dashboard:'Перейти к панели', notifications:'Уведомления', changeTheme:'Изменить тему', navigateOn:'Автоматическая навигация включена; нажмите модуль, чтобы открыть его', navigateOff:'Автоматическая навигация выключена; нажмите модуль, чтобы открыть меню', organizationLogo:'Логотип организации', logoBackgroundTitle:'Фон логотипа', logoBackgroundHint:'Выберите фон логотипа в верхней панели.', backgroundNone:'Без фона', backgroundDark:'Тёмный фон', backgroundWhite:'Белый фон',
  },
  ja: {
    settingsTitle:'一般設定', settingsDescription:'アクセントカラーと言語を選択します。ライト・ダークモードは上部ヘッダーから切り替えられます。', accentTitle:'アクセントカラー', accentDescription:'選択した色はワークスペースにすぐ反映されます。「変更を保存」で保持し、保存せずに移動すると元の色に戻ります。', preview:'プレビュー', primaryAction:'主な操作', selectedItem:'選択中の項目', languageTitle:'表示言語', languageDescription:'ペルシア語、英語、アラビア語、簡体字中国語、フランス語、スペイン語、ドイツ語、ロシア語、日本語、ブラジルポルトガル語。', languageHelp:'言語を変更するには、設定 → 一般を開き、言語を選んで「変更を保存」を押してください。', languageLabel:'言語', saveChanges:'変更を保存', blue:'青', green:'緑', red:'赤', yellow:'黄', purple:'紫', customColor:'カスタムカラー', accentPreviewHint:'選択した色のプレビュー', openSidebar:'サイドバーを開く', unlockSidebar:'サイドバーのロックを解除', lockSidebar:'サイドバーをロック', themeSystem:'テーマ：システム', themeLight:'テーマ：ライト', themeDark:'テーマ：ダーク', viewProfile:'サイドバーでプロフィールを表示', admin:'管理者', user:'ユーザー', dashboard:'ダッシュボードへ移動', notifications:'通知', changeTheme:'テーマを変更', navigateOn:'自動ナビゲーションが有効です。クリックしてモジュールを開きます', navigateOff:'自動ナビゲーションは無効です。クリックしてメニューを開きます', organizationLogo:'組織のロゴ', logoBackgroundTitle:'ロゴの背景', logoBackgroundHint:'ヘッダーに表示するロゴの背景を選択します。', backgroundNone:'背景なし', backgroundDark:'暗い背景', backgroundWhite:'白い背景',
  },
  'pt-BR': {
    settingsTitle:'Configurações gerais', settingsDescription:'Escolha a cor de destaque e o idioma. Os modos claro e escuro ficam disponíveis no cabeçalho.', accentTitle:'Cor de destaque', accentDescription:'A cor escolhida aparece imediatamente na área de trabalho. Clique em “Salvar alterações” para mantê-la; sair sem salvar restaura a cor anterior.', preview:'Pré-visualização', primaryAction:'Ação principal', selectedItem:'Item selecionado', languageTitle:'Idioma de exibição', languageDescription:'Persa, inglês, árabe, chinês simplificado, francês, espanhol, alemão, russo, japonês e português brasileiro.', languageHelp:'Para mudar o idioma, abra Configurações → Geral, escolha um idioma e clique em “Salvar alterações”.', languageLabel:'Idioma', saveChanges:'Salvar alterações', blue:'Azul', green:'Verde', red:'Vermelho', yellow:'Amarelo', purple:'Roxo', customColor:'Cor personalizada', accentPreviewHint:'Pré-visualização da cor escolhida', openSidebar:'Abrir barra lateral', unlockSidebar:'Desbloquear barra lateral', lockSidebar:'Bloquear barra lateral', themeSystem:'Tema: sistema', themeLight:'Tema: claro', themeDark:'Tema: escuro', viewProfile:'Ver perfil na barra lateral', admin:'administrador', user:'Usuário', dashboard:'Ir para o painel', notifications:'Notificações', changeTheme:'Alterar tema', navigateOn:'A navegação automática está ativa; clique em um módulo para abri-lo', navigateOff:'A navegação automática está desativada; clique em um módulo para abrir o menu', organizationLogo:'Logotipo da organização', logoBackgroundTitle:'Fundo do logotipo', logoBackgroundHint:'Escolha o fundo exibido atrás do logotipo no cabeçalho.', backgroundNone:'Sem fundo', backgroundDark:'Fundo escuro', backgroundWhite:'Fundo branco',
  },
};

const invalidLogoBackgroundMessages: Record<Locale, string> = {
  fa: 'پس‌زمینه لوگو باید بدون پس‌زمینه، تیره یا سفید باشد.',
  en: 'Logo background must be none, dark, or white.',
  ar: 'يجب أن تكون خلفية الشعار بلا خلفية أو داكنة أو بيضاء.',
  'zh-CN': '徽标背景必须为无背景、深色或白色。',
  fr: 'Le fond du logo doit être absent, sombre ou blanc.',
  es: 'El fondo del logotipo debe ser transparente, oscuro o blanco.',
  de: 'Der Logo-Hintergrund muss transparent, dunkel oder weiß sein.',
  ru: 'Фон логотипа должен быть прозрачным, тёмным или белым.',
  ja: 'ロゴの背景は、なし・暗色・白色から選択してください。',
  'pt-BR': 'O fundo do logotipo deve ser sem fundo, escuro ou branco.',
};

export function uiMessage(locale: Locale, key: UiMessage): string {
  if (key === 'invalidLogoBackground') return invalidLogoBackgroundMessages[locale];
  return messages[locale][key];
}
