import type { UiMessage } from '../types';

const messages = {

    settingsTitle:'Paramètres généraux', settingsDescription:'Choisissez la couleur principale et la langue. Le mode clair ou sombre reste accessible dans l’en-tête.', accentTitle:'Couleur principale', accentDescription:'La couleur choisie est prévisualisée immédiatement. Cliquez sur « Enregistrer » pour la conserver ; quitter sans enregistrer rétablit la couleur précédente.', preview:'Aperçu', primaryAction:'Action principale', selectedItem:'Élément sélectionné', languageTitle:'Langue d’affichage', languageDescription:'Persan, anglais, arabe, chinois simplifié, français, espagnol, allemand, russe, japonais et portugais brésilien.', languageHelp:'Pour changer de langue, ouvrez Paramètres → Général, choisissez une langue, puis cliquez sur « Enregistrer les modifications ».', languageLabel:'Langue', saveChanges:'Enregistrer', blue:'Bleu', green:'Vert', red:'Rouge', yellow:'Jaune', purple:'Violet', customColor:'Couleur personnalisée', accentPreviewHint:'Aperçu de la couleur choisie', openSidebar:'Ouvrir le menu', unlockSidebar:'Déverrouiller le menu', lockSidebar:'Verrouiller le menu', themeSystem:'Thème : système', themeLight:'Thème : clair', themeDark:'Thème : sombre', viewProfile:'Voir le profil dans le menu', admin:'administrateur', user:'Utilisateur', dashboard:'Aller au tableau de bord', notifications:'Notifications', changeTheme:'Changer de thème', navigateOn:'Navigation automatique activée ; cliquez sur un module pour l’ouvrir', navigateOff:'Navigation automatique désactivée ; cliquez sur un module pour ouvrir son menu', organizationLogo:'Logo de l’organisation', logoBackgroundTitle:'Arrière-plan du logo', logoBackgroundHint:'Choisissez l’arrière-plan du logo dans l’en-tête.', backgroundNone:'Sans arrière-plan', backgroundDark:'Arrière-plan sombre', backgroundWhite:'Arrière-plan blanc',
    invalidLogoBackground: 'Le fond du logo doit être absent, sombre ou blanc.',
} satisfies Record<UiMessage, string>;

export default messages;
